### ISSUE TITLE
[bug] Bug when used with Symfony HttpClient

### ISSUE THREAD

**Issue by ging-dev** [swow/swow#121]
**Describe the bug / 问题描述**
```
Warning: [Fatal error in R2] Uncaught Symfony\Component\HttpClient\Exception\TransportException: Transfer closed with outstanding data remaining from chunked response. in /home/gingdev/code/gingdev/telebot/vendor/symfony/http-client/Response/NativeResponse.php:311
Stack trace:
#0 /home/gingdev/code/gingdev/telebot/vendor/symfony/http-client/Response/TransportResponseTrait.php(176): Symfony\Component\HttpClient\Response\NativeResponse::perform(Object(Symfony\Component\HttpClient\Internal\NativeClientState), Array)
#1 /home/gingdev/code/gingdev/telebot/vendor/symfony/http-client/Response/CommonResponseTrait.php(68): Symfony\Component\HttpClient\Response\NativeResponse::stream(Array)
#2 /home/gingdev/code/gingdev/telebot/momo.php(16): Symfony\Component\HttpClient\Response\NativeResponse->getContent()
#3 [internal function]: {closure}()
#4 {main}

Next Symfony\Component\HttpClient\Exception\TransportException: Transfer closed with outstanding data remaining from chunked response. in /home/gingdev/code/gingdev/telebot/vendor/symfony/http-client/Chunk/ErrorChunk.php:89
Stack trace:
#0 /home/gingdev/code/gingdev/telebot/vendor/symfony/http-client/Response/TransportResponseTrait.php(285): Symfony\Component\HttpClient\Chunk\ErrorChunk->getContent()
#1 /home/gingdev/code/gingdev/telebot/vendor/symfony/http-client/Response/CommonResponseTrait.php(68): Symfony\Component\HttpClient\Response\NativeResponse::stream(Array)
#2 /home/gingdev/code/gingdev/telebot/momo.php(16): Symfony\Component\HttpClient\Response\NativeResponse->getContent()
#3 [internal function]: {closure}()
#4 {main}
```

**To Reproduce / 如何复现**
```php
<?php

// >_ php -n -d extension=./vendor/swow/swow/ext/modules/swow.so

use Swow\Coroutine;
use Swow\Sync\WaitReference;
use Symfony\Component\HttpClient\HttpClient;

require __DIR__.'/vendor/autoload.php';

$wr = new WaitReference();

Coroutine::run(static function () use ($wr) {
    $client = HttpClient::create();
    $resp = $client->request('GET', 'https://www.baidu.com');
    echo $resp->getContent();
});

WaitReference::wait($wr);
```

1. Do something first / 先做了什么
2. Then do another / 然后做了什么
3. Finally the software blew up / 它炸了

**Expected behavior / 正确的行为**

**Outputs / 程序输出**

**Runtime Environment / 运行环境**

OS:

```plain
Ubuntu 22.04
```

PHP: `8.1`

Swow:
```
Swow
Status => enabled
Author => Swow Team
Link => https://github.com/swow/swow
Contact => Twosee <twosee@php.net>
Version => 0.1.0 ( NTS )
Built => Jun 14 2022 08:33:53
Context => boost-context
Scheduler => libuv-event
With => OpenSSL 3.0.2 15 Mar 2022, cURL 7.81.0
```

**Additional context / 补充说明**

**Comment by dixyes** [comment]
你用的啥Swow版本呢 git的提交号 还是github的tarball还是什么办法下来的

**Comment by ging-dev** [comment]
> 你用的啥Swow版本呢 git的提交号 还是github的tarball还是什么办法下来的

ebd7183f0af42d60666bd44c2134d2bc42ff3cb6

**Comment by twose** [comment]
没有复现，我这里是正常的，可以试试通过 `./vendor/bin/swow-builder '--rebuild' '--debug' '--install'` 来编译，然后 `CAT_DEBUG=1 php -d extension=swow your_file.php` 来执行，把日志发一下。

**Comment by ging-dev** [comment]
> 没有复现，我这里是正常的，可以试试通过 `./vendor/bin/swow-builder '--rebuild' '--debug' '--install'` 来编译，然后 `CAT_DEBUG=1 php -d extension=swow your_file.php` 来执行，把日志发一下。

Looks like adding `-n` threw the error, it was my fault.

**Comment by twose** [comment]
猜测是你 -n 导致缺少 curl 扩展，symfony/http-client 自动走了 native client （也就是 PHP 自带的 stream），但是估计你 -n 以后又没有 openssl 扩展，导致无法访问 https 网站报错。
