### ISSUE TITLE
[bug] 执行 swow-builder 报错

### ISSUE THREAD

**Issue by huangdijia** [swow/swow#138]
版本：v0.2.0-alpha.1

```shell
$ ./vendor/bin/swow-builder

Fatal error: Uncaught Error: Call to undefined function Swow\Utils\passthru() in /Users/hdj/gitroot/test/vendor/swow/swow/ext/bin/swow-builder:54
Stack trace:
#0 /Users/hdj/gitroot/test/vendor/swow/swow/ext/bin/swow-builder(97): {closure}('Configure', Array)
#1 /Users/hdj/gitroot/test/vendor/bin/swow-builder(120): include('/Users/hdj/gitr...')
#2 {main}
  thrown in /Users/hdj/gitroot/test/vendor/swow/swow/ext/bin/swow-builder on line 54
```

**Comment by dixyes** [comment]
composer install了吗？`composer require swow/swow:dev-develop`
建议直接phpize configure make
那个脚本基本上只能composer用

**Comment by huangdijia** [comment]
有 composer install 了的，不然 vendor/bin 目录下也没有 swow-builder 这个脚本

**Comment by twose** [comment]
@huangdijia 看下这个patch以后是不是OK了

**Comment by huangdijia** [comment]
好的

**Comment by huangdijia** [comment]
```php
dirname(__DIR__, 4) . '/autoload.php', // for user on swow/swow
```

这里应该是 `dirname(__DIR__, 5)`。

解决了 `Call to undefined function Swow\Utils\passthru() ` 的问题，又来了新的问题。

```shell
Fatal error: Uncaught Error: Class "Swow\Socket" not found in /Users/hdj/gitroot/test/vendor/hyperf/engine-swow/constants.php:16
Stack trace:
#0 /Users/hdj/gitroot/test/vendor/composer/autoload_real.php(55): require()
#1 /Users/hdj/gitroot/test/vendor/composer/autoload_real.php(38): composerRequire544d778a57acd5ad1f2170558981c16d('000c1c7b9a55bdf...', '/Users/hdj/gitr...')
#2 /Users/hdj/gitroot/test/vendor/autoload.php(25): ComposerAutoloaderInit544d778a57acd5ad1f2170558981c16d::getLoader()
#3 /Users/hdj/gitroot/test/vendor/swow/swow/ext/bin/swow-builder(18): require('/Users/hdj/gitr...')
#4 /Users/hdj/gitroot/test/vendor/bin/swow-builder(120): include('/Users/hdj/gitr...')
#5 {main}
  thrown in /Users/hdj/gitroot/test/vendor/hyperf/engine-swow/constants.php on line 16
```

**Comment by twose** [comment]
那就是hyperf的问题了，我这个脚本都不用扩展，为什么会调到hyperf的autoloader，而且还强制用到Socket...
@limingxinleo

**Comment by twose** [comment]
https://github.com/hyperf/engine-swow/blob/master/constants.php

@limingxinleo  因为是autoloadfile所以是不管用不用都强制加载的，应该判断一下有Swow扩展再去define... 不然没使用到Swow的脚本也会被强制要求依赖Swow了，还有这个define太邪恶了

**Comment by limingxinleo** [comment]
@huangdijia 
![image](https://user-images.githubusercontent.com/16648551/200735576-d30bf834-7dd3-4020-a00a-a283ca82564c.png)

提个PR，把这些去掉吧

**Comment by twose** [comment]
理论上这些常量都不该有，要么Hyperf再包一层常量，不然会出现混用

**Comment by twose** [comment]
理论上这些常量都不该有，要么Hyperf再包一层常量，不然会出现混用
