### ISSUE TITLE
[bug] Swow\Psr7\Client\Client 不支持content-length为空的返回么?

### ISSUE THREAD

**Issue by okool** [swow/swow#141]
环境:
macos
php8.1
"swow/swow": "dev-develop"

使用的是 `php -S 127.0.0.1:8080` 启的服务.
 
```
$client = new Client();
$domain = '127.0.0.1';
$request = Psr7::createRequest(method: 'GET', uri: '/index.php');
$response = $client
    ->connect($domain, 8080)
    ->sendRequest($request);

echo 'Response', Psr7::stringifyResponse($response);
```
返回异常.

```
Fatal error: Uncaught Swow\Http\ParserException: Expected MESSAGE_COMPLETE, got NONE in /Volumes/Data/PhpProject/Arkin/AcHyperf/vendor/swow/swow/lib/swow-library/src/Http/Protocol/ReceiverTrait.php:481
Stack trace:
#0 /Volumes/Data/PhpProject/Arkin/AcHyperf/vendor/swow/swow/lib/swow-library/src/Psr7/Client/Client.php(107): Swow\Psr7\Client\Client->recvMessageEntity()
#1 /Volumes/Data/PhpProject/Arkin/AcHyperf/vendor/swow/swow/lib/swow-library/src/Psr7/Client/Client.php(133): Swow\Psr7\Client\Client->recvResponseEntity()
#2 /Volumes/Data/PhpProject/Arkin/AcHyperf/bin/swow.php(18): Swow\Psr7\Client\Client->sendRequest(Object(Swow\Psr7\Message\Request))
#3 {main}

Next Swow\Psr7\Client\ClientRequestException: Protocol Parsing Error in /Volumes/Data/PhpProject/Arkin/AcHyperf/vendor/swow/swow/lib/swow-library/src/Http/Protocol/ReceiverTrait.php:517
Stack trace:
#0 /Volumes/Data/PhpProject/Arkin/AcHyperf/vendor/swow/swow/lib/swow-library/src/Psr7/Client/Client.php(107): Swow\Psr7\Client\Client->recvMessageEntity()
#1 /Volumes/Data/PhpProject/Arkin/AcHyperf/vendor/swow/swow/lib/swow-library/src/Psr7/Client/Client.php(133): Swow\Psr7\Client\Client->recvResponseEntity()
#2 /Volumes/Data/PhpProject/Arkin/AcHyperf/bin/swow.php(18): Swow\Psr7\Client\Client->sendRequest(Object(Swow\Psr7\Message\Request))
#3 {main}
  thrown in /Volumes/Data/PhpProject/Arkin/AcHyperf/vendor/swow/swow/lib/swow-library/src/Http/Protocol/ReceiverTrait.php on line 517

```

curl返回正常:

```
➜  8.1.12  curl -v http://127.0.0.1:8080/index.php
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /index.php HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Host: 127.0.0.1:8080
< Date: Thu, 24 Nov 2022 07:05:06 GMT
< Connection: close
< X-Powered-By: PHP/8.1.12
< Content-type: text/html; charset=UTF-8
< 
* Closing connection 0
ok%  
```

GuzzleHttp解析正常.
Postman浏览器解析正常.

**Comment by twose** [comment]
修复已包含在[v0.3.2-alpha](https://github.com/swow/swow/releases/tag/v0.3.2-alpha)中
