### ISSUE TITLE
[bug] enableCrypto Ignoring stale global SSL error

### ISSUE THREAD

**Issue by xywf221** [swow/swow#150]
**Describe the bug / 问题描述**
Swow\Socket 接收一个非TLS请求后,然后启用加密控制台会一直输出 
`Notice: [Notice in R2] Ignoring stale global SSL error`

**To Reproduce / 如何复现**
使用以下代码
```php
<?php
$server = new Socket(Socket::TYPE_TCP);
$server->bind('127.0.0.1', 4433)->listen();
while (true) {
    $conn = $server->accept();
    Coroutine::run(static function () use ($conn) {
        $conn->enableCrypto([
            'certificate' => 'x',
            'certificate_key' => 'x',
        ]);
    });
}
```
证书跟key我就不贴了
启动服务后执行 `telnet 127.0.0.1 4433` 

**Expected behavior / 正确的行为**
抛出异常 Enable Crypto failed reason : xxxxx

**Outputs / 程序输出**
```
Notice: [Notice in R2] Ignoring stale global SSL error 
Stack trace:
#0 /Users/dmls/PhpstormProjects/swow-test/src/Command/ServerCommand.php(37): Swow\Socket->enableCrypto(Array)
#1 [internal function]: xywf221\Trojan\Command\ServerCommand::xywf221\Trojan\Command\{closure}()
#2 /Users/dmls/PhpstormProjects/swow-test/src/Command/ServerCommand.php(40): Swow\Coroutine::run(Object(Closure))
```

**Runtime Environment / 运行环境**

```plain
macOS 12.6.1 21G217 x86_64 
```

PHP: PHP 8.1.13 (cli) (built: Nov 24 2022 16:11:31) (NTS)

Swow

```
Status => enabled
Author => Swow Team
Link => https://github.com/swow/swow
Contact => Twosee <twosee@php.net>
Version => 1.0.1-dev ( NTS )
Built => Jan  3 2023 23:41:49
Context => boost-context
Scheduler => libuv-event
With => OpenSSL 1.1.1s  1 Nov 2022, cURL 7.86.0
```

**Comment by xywf221** [comment]
这里追加下证书是使用acme.sh生成的，如果使用xxx.com.cer 就会出现以上问题，但是如果换成fullchain.cer就没问题.

**Comment by xywf221** [comment]
个人环境编译导致换成用lwmbs编译出来的静态php就没问题

**Comment by dixyes** [comment]
我觉得大概跟php swow lwmbs都没啥关系 应该是你连接到的openssl的配置文件与其他环境的不同导致的，这个notice应该可以安全的忽略

**Comment by twose** [comment]
是编译时的OpenSSL和链接到的OpenSSL版本不同导致的报错死循环（出现了 ERR_peek_error() 返回了非NULL 而 ERR_peek_error_data() 返回了 NULL 的情况导致代码一直在循环里出不来）。
