### ISSUE TITLE
[bug] 与 elastic apm agent for php 一起使用，当进程结束时会报 fatal error

### ISSUE THREAD

**Issue by lanlin** [swow/swow#193]
开启 elastic apm 扩展，单纯的执行 `php -i` 就会出现以下错误。
关闭该扩展则不会有问题。关闭 swow 后，单独使用 elastic apm 扩展也不会有问题。

### php
```shell
PHP 8.2.6 (cli) (built: Jun  1 2023 08:19:04) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
```

### swow
```shell
Swow

Status => enabled
Author => Swow Team
Link => https://github.com/swow/swow
Contact => Twosee <twosee@php.net>
Version => 1.2.0 ( NTS DEBUG )
Built => Jun  1 2023 09:44:01
Context => boost-context
Scheduler => libuv-event
SSL => OpenSSL 3.0.9 30 May 2023
cURL => libcurl/8.1.2-DEV OpenSSL/3.0.9 zlib/1.2.7 libssh2/1.11.0 nghttp2/1.53.0
```

### core dump:
```shell
sh-4.2# php a.php 
Fatal error: Kill Coroutine#0 failed when destruct object, reason: Kill coroutine 0 failed, reason: Coroutine is not in executing in Unknown on line 0
Aborted (core dumped)
sh-4.2# gdb php -c core
GNU gdb (GDB) Red Hat Enterprise Linux 8.0.1-36.amzn2.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.
[New LWP 399]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `php a.php'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      }
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f60a356f148 in __GI_abort () at abort.c:79
#2  0x00007f609b3292a6 in cat_abort () at deps/libcat/src/cat_error.c:122
#3  0x00007f609b2d0784 in swow_log_va_list_standard (type=CAT_LOG_TYPE_CORE_ERROR, module_name=0x7f609b397714 "COROUTINE", 
    function=0x7f609b397f80 <__FUNCTION__.22973> "swow_coroutine_dtor_object", file=0x7f609b39771e "src/swow_coroutine.c", line=144, code=-3, 
    format=0x7f609b3977f8 "Kill Coroutine#%lu failed when destruct object, reason: %s", args=0x7ffc229ab078) at src/swow_log.c:140
#4  0x00007f609b2d0871 in swow_log_standard (type=CAT_LOG_TYPE_CORE_ERROR, module_name=0x7f609b397714 "COROUTINE", 
    function=0x7f609b397f80 <__FUNCTION__.22973> "swow_coroutine_dtor_object", file=0x7f609b39771e "src/swow_coroutine.c", line=144, code=-3, 
    format=0x7f609b3977f8 "Kill Coroutine#%lu failed when destruct object, reason: %s") at src/swow_log.c:156
#5  0x00007f609b2d828a in swow_coroutine_dtor_object (object=0x7f609ae22208) at src/swow_coroutine.c:144
#6  0x0000000000921bfe in zend_objects_store_call_destructors ()
#7  0x00000000008674aa in shutdown_destructors ()
#8  0x000000000087c1f0 in zend_call_destructors ()
#9  0x00000000008001f9 in php_request_shutdown ()
#10 0x0000000000979fed in do_cli ()
#11 0x000000000045df09 in main ()
(gdb) l
46        int ret = INLINE_SYSCALL (tgkill, 3, pid, tid, sig);
47
48        __libc_signal_restore_set (&set);
49
50        return ret;
51      }
52      libc_hidden_def (raise)
53      weak_alias (raise, gsignal)
(gdb) l
Line number 54 out of range; ../sysdeps/unix/sysv/linux/raise.c has 53 lines.
```

**Comment by lanlin** [comment]
以下为重现方式，额，稍微麻烦了点，因为在 bref 的容器环境中 ...

### Dockerfile
```dockerfile
# https://bref.sh/docs/environment/php.html#extensions-installed-and-enabled
ARG PHP_VERSION=82
ARG BREF_VERSION=2
FROM bref/build-php-82:2 as ext


# Build Swow extension
RUN mkdir /tmp/swow && \
    curl -L https://github.com/swow/swow/archive/refs/tags/v1.2.0.tar.gz | tar -C /tmp/swow -zx --strip-components=1
RUN cd /tmp/swow/ext && phpize && \
    ./configure --enable-swow-debug
RUN cd /tmp/swow/ext && make && make install && make test
RUN cp `php-config --extension-dir`/swow.so /tmp/swow.so
RUN echo 'extension=swow.so' > /tmp/ext-swow.ini
RUN php /bref/lib-copy/copy-dependencies.php /tmp/swow.so /tmp/extension-libs


# Build Elastic APM extension
RUN \
    LD_LIBRARY_PATH=/lib64:/lib yum install -y libcurl-devel openssl-devel \
    && mkdir /tmp/apm \
    && curl -L https://github.com/elastic/apm-agent-php/archive/refs/tags/v1.8.4.tar.gz | tar -C /tmp/apm -zx --strip-components=1 \
    && cd /tmp/apm/src/ext \
    && phpize \
    && CFLAGS="-std=gnu99" ./configure --enable-elastic_apm \
    && make clean \
    && make \
    && make install \
    && echo 'extension=elastic_apm.so' > /tmp/elastic-apm.ini


# Build the final image from the amazon image that is close to the production environment
FROM bref/php-82:2 as finals


# Copy swow to the final image
COPY --from=ext /tmp/swow.so /opt/bref/extensions/swow.so
COPY --from=ext /tmp/ext-swow.ini /opt/bref/etc/php/conf.d/ext-swow.ini
COPY --from=ext /tmp/extension-libs /opt/lib


# Copy elastic-apm to the final image
COPY --from=ext /tmp/apm/src/ext/modules/elastic_apm.so /opt/bref/extensions/elastic_apm.so
COPY --from=ext /tmp/elastic-apm.ini /opt/bref/etc/php/conf.d/elastic-apm.ini


# Copy other extensions to the final image
# layer version 0.x for bref v1 and 1.x for bref v2
COPY --from=bref/extra-redis-igbinary-php-82:1.2.2 /opt /opt


# Copy final results
FROM bref/php-82:2
COPY --from=finals /opt /opt
COPY --from=finals /var/task /var/task
CMD ["index.php"]
```

### composer
```composer.json
{
  "autoload": {
    "psr-4": {}
  },
  "require": {
    "php": ">=8.2.0",
    "lanlin/elastic-apm-agent": "^1.8",
    "swow/swow": "^1.2"
  }
}
```

### 容器启动时环境变量
```shell
# ------------------------------------------------------------------------------
# Elastic APM
# ------------------------------------------------------------------------------
ELASTIC_APM_ENABLED=true
ELASTIC_APM_LOG_LEVEL=WARNING
ELASTIC_APM_ENVIRONMENT=local
ELASTIC_APM_BOOTSTRAP_PHP_PART_FILE='/var/task/vendor/lanlin/elastic-apm-agent/src/bootstrap_php_part.php'

# ------------------------------------------------------------------------------
# Bref Images
# ------------------------------------------------------------------------------
HANDLER=index.php
BREF_PING_DISABLE=1
AWS_ACCESS_KEY_ID=fake
AWS_SESSION_TOKEN=fake
AWS_SECRET_ACCESS_KEY=fake
```

### index.php (容器内的路径为 /var/task/index.php)
```php
<?php

require './vendor/autoload.php';
```

### 进入容器后执行
```shell
sh-4.2# php index.php 

Fatal error: Kill Coroutine#0 failed when destruct object, reason: Kill coroutine 0 failed, reason: Coroutine is not in executing in Unknown on line 0
Aborted (core dumped)
```

**Comment by lanlin** [comment]
以下为重现方式，额，稍微麻烦了点，因为在 bref 的容器环境中 ...

### Dockerfile
```dockerfile
# https://bref.sh/docs/environment/php.html#extensions-installed-and-enabled
ARG PHP_VERSION=82
ARG BREF_VERSION=2
FROM bref/build-php-82:2 as ext


# Build Swow extension
RUN mkdir /tmp/swow && \
    curl -L https://github.com/swow/swow/archive/refs/tags/v1.2.0.tar.gz | tar -C /tmp/swow -zx --strip-components=1
RUN cd /tmp/swow/ext && phpize && \
    ./configure --enable-swow-debug
RUN cd /tmp/swow/ext && make && make install && make test
RUN cp `php-config --extension-dir`/swow.so /tmp/swow.so
RUN echo 'extension=swow.so' > /tmp/ext-swow.ini
RUN php /bref/lib-copy/copy-dependencies.php /tmp/swow.so /tmp/extension-libs


# Build Elastic APM extension
RUN \
    LD_LIBRARY_PATH=/lib64:/lib yum install -y libcurl-devel openssl-devel \
    && mkdir /tmp/apm \
    && curl -L https://github.com/elastic/apm-agent-php/archive/refs/tags/v1.8.4.tar.gz | tar -C /tmp/apm -zx --strip-components=1 \
    && cd /tmp/apm/src/ext \
    && phpize \
    && CFLAGS="-std=gnu99" ./configure --enable-elastic_apm \
    && make clean \
    && make \
    && make install \
    && echo 'extension=elastic_apm.so' > /tmp/elastic-apm.ini


# Build the final image from the amazon image that is close to the production environment
FROM bref/php-82:2 as finals


# Copy swow to the final image
COPY --from=ext /tmp/swow.so /opt/bref/extensions/swow.so
COPY --from=ext /tmp/ext-swow.ini /opt/bref/etc/php/conf.d/ext-swow.ini
COPY --from=ext /tmp/extension-libs /opt/lib


# Copy elastic-apm to the final image
COPY --from=ext /tmp/apm/src/ext/modules/elastic_apm.so /opt/bref/extensions/elastic_apm.so
COPY --from=ext /tmp/elastic-apm.ini /opt/bref/etc/php/conf.d/elastic-apm.ini


# Copy other extensions to the final image
# layer version 0.x for bref v1 and 1.x for bref v2
COPY --from=bref/extra-redis-igbinary-php-82:1.2.2 /opt /opt


# Copy final results
FROM bref/php-82:2
COPY --from=finals /opt /opt
COPY --from=finals /var/task /var/task
CMD ["index.php"]
```

### composer
```composer.json
{
  "autoload": {
    "psr-4": {}
  },
  "require": {
    "php": ">=8.2.0",
    "lanlin/elastic-apm-agent": "^1.8",
    "swow/swow": "^1.2"
  }
}
```

### 容器启动时环境变量
```shell
# ------------------------------------------------------------------------------
# Elastic APM
# ------------------------------------------------------------------------------
ELASTIC_APM_ENABLED=true
ELASTIC_APM_LOG_LEVEL=WARNING
ELASTIC_APM_ENVIRONMENT=local
ELASTIC_APM_BOOTSTRAP_PHP_PART_FILE='/var/task/vendor/lanlin/elastic-apm-agent/src/bootstrap_php_part.php'

# ------------------------------------------------------------------------------
# Bref Images
# ------------------------------------------------------------------------------
HANDLER=index.php
BREF_PING_DISABLE=1
AWS_ACCESS_KEY_ID=fake
AWS_SESSION_TOKEN=fake
AWS_SECRET_ACCESS_KEY=fake
```

### index.php (容器内的路径为 /var/task/index.php)
```php
<?php

require './vendor/autoload.php';
```

### 进入容器后执行
```shell
sh-4.2# php index.php 

Fatal error: Kill Coroutine#0 failed when destruct object, reason: Kill coroutine 0 failed, reason: Coroutine is not in executing in Unknown on line 0
Aborted (core dumped)
```
