### ISSUE TITLE
[bug] WebSocketClient error

### ISSUE THREAD

**Issue by xywf221** [swow/swow#219]
**Describe the bug / 问题描述**
目前有个websocketServer，使用客户端连接上去没多少时间就会出现报错

**To Reproduce / 如何复现**
简短代码
```
$this->client = (new Psr7\Client\Client())->connect($host, $port);
$request = Psr7\Psr7::createRequest('GET', $path);
while(true){
  $frame = $this->client->recvWebSocketFrame();
}
```
websocketServer地址如果需要请联系我，这是一个私人qq机器人ws服务

**Expected behavior / 正确的行为**
正常收包不报错

**Outputs / 程序输出**
```
[ERROR] Swow\SocketException: Connection closed normally by peer while waiting for data in /Users/dmls/PhpstormProjects/qqbot/vendor/swow/swow/lib/swow-library/src/Http/Protocol/ReceiverTrait.php:643
Stack trace:
#0 /Users/dmls/PhpstormProjects/qqbot/vendor/swow/swow/lib/swow-library/src/Http/Protocol/ReceiverTrait.php(643): Swow\Socket->recvData(Object(Swow\Buffer), 0)
#1 /Users/dmls/PhpstormProjects/qqbot/vendor/swow/swow/lib/swow-library/src/Psr7/Protocol/WebSocketTrait.php(31): Swow\Psr7\Client\Client->recvWebSocketFrameEntity()
#2 /Users/dmls/PhpstormProjects/qqbot/app/Components/OPQ/WebSocketClient.php(85): Swow\Psr7\Client\Client->recvWebSocketFrame()
#3 /Users/dmls/PhpstormProjects/qqbot/runtime/container/proxy/App_Components_OPQ_WebSocketEventSink.proxy.php(31): App\Components\OPQ\WebSocketClient->recv()
#4 /Users/dmls/PhpstormProjects/qqbot/app/Process/RobotProcess.php(33): App\Components\OPQ\WebSocketEventSink->sink()
#5 /Users/dmls/PhpstormProjects/qqbot/vendor/hyperf/process/src/AbstractProcess.php(135): App\Process\RobotProcess->handle()
#6 /Users/dmls/PhpstormProjects/qqbot/vendor/hyperf/coroutine/src/Coroutine.php(68): Hyperf\Process\AbstractProcess->Hyperf\Process\{closure}()
#7 [internal function]: Hyperf\Coroutine\Coroutine::Hyperf\Coroutine\{closure}()
#8 {main}
```

PHP:  PHP 8.2.10 (cli) (built: Aug 31 2023 19:16:09) (NTS)

Swow:  1.3.2-dev-8bd6d591-dirty ( NTS )

**Comment by xywf221** [comment]
补充一下使用go跟postman试验了下 均不会出问题

**Comment by twose** [comment]
这个是 Hyperf 没做兜底处理，其实可以屏蔽掉。

仔细看异常信息其实就是连接正常关闭了，抛出是为了让程序逻辑不继续往下运行，因为 Swow 收敛了返回值为单个强类型，而不会返回 null，这样写出来的代码健壮性更好。

**Comment by xywf221** [comment]
> 这个是 Hyperf 没做兜底处理，其实可以屏蔽掉。
> 
> 仔细看异常信息其实就是连接正常关闭了，抛出是为了让程序逻辑不继续往下运行，因为 Swow 收敛了返回值为单个强类型，而不会返回 null，这样写出来的代码健壮性更好。

忘了回复了原因已经排查清楚了swow提供的ws客户端太底层了,有的ws服务器会定时向客户端发送ping frame如果客户端不回复pong frame就会认为客户端掉线了

**Comment by xywf221** [comment]
提供简单的封装代码以供后面的人解决

```php
    /**
     * @throws SocketException
     */
    public function recv(float $timeout = -1): string
    {
        $frame = $this->client->recvWebSocketFrame();
        switch ($frame->getOpcode()) {
            case Opcode::CLOSE:
                throw new SocketException('Connection closed');
            case Opcode::PING:
            case Opcode::PONG:
                $this->sendPONGFrame();
                return $this->recv($timeout);
        }
        return $frame->getPayloadData()->getContents();
    }

    private function sendPONGFrame(): void
    {
        $pongFrame = Psr7\Psr7::createWebSocketFrame(Opcode::PONG, null, true, true);
        $this->client->sendWebSocketFrame($pongFrame);
    }
```
