### ISSUE TITLE
[discussion] 版本升级导致与镜像版本不一致产生异常 有什么比较平滑过渡的方案吗？

### ISSUE THREAD

**Issue by stevennight** [swow/swow#254]
比如我镜像extension版本是1.5.2的，
但是我项目composer update到了1.5.3
直接就是抛出异常：
```
PHP Fatal error:  Uncaught Error: Swow extension version mismatch, required: ^1.5.3, actual: 1.5.2 in /opt/www/vendor/swow/swow/lib/swow-library/src/bootstrap.php:26
Stack trace:
#0 /opt/www/vendor/composer/autoload_real.php(41): require()
#1 /opt/www/vendor/composer/autoload_real.php(45): {closure}('782da01c914ccdb...', '/opt/www/vendor...')
#2 /opt/www/vendor/autoload.php(25): ComposerAutoloaderInit72ac0b8252822528c034bbf39a2eb746::getLoader()
#3 /opt/www/yii(14): require('/opt/www/vendor...')
#4 {main}
  thrown in /opt/www/vendor/swow/swow/lib/swow-library/src/bootstrap.php on line 26

Fatal error: Uncaught Error: Swow extension version mismatch, required: ^1.5.3, actual: 1.5.2 in /opt/www/vendor/swow/swow/lib/swow-library/src/bootstrap.php on line 26

Error: Swow extension version mismatch, required: ^1.5.3, actual: 1.5.2 in /opt/www/vendor/swow/swow/lib/swow-library/src/bootstrap.php on line 26

Call Stack:
    0.0011     489000   1. {main}() /opt/www/yii:0
    0.0012     492192   2. require('/opt/www/vendor/autoload.php') /opt/www/yii:14
    0.0013     598032   3. ComposerAutoloaderInit72ac0b8252822528c034bbf39a2eb746::getLoader() /opt/www/vendor/autoload.php:25
    0.0077    1493448   4. {closure:/opt/www/vendor/composer/autoload_real.php:37-43}($fileIdentifier = '782da01c914ccdbad9f63af9f0782a69', $file = '/opt/www/vendor/composer/../swow/swow/lib/swow-library/src/bootstrap.php') /opt/www/vendor/composer/autoload_real.php:45
    0.0077    1496456   5. require('/opt/www/vendor/swow/swow/lib/swow-library/src/bootstrap.php') /opt/www/vendor/composer/autoload_real.php:41
```

有什么比较平滑过渡的方案吗？

**Comment by xywf221** [comment]
composer中把swow的依赖的版本号写死？

**Comment by stevennight** [comment]
> composer中把swow的依赖的版本号写死？

实在不行最安全就这样了 hhh

**Comment by twose** [comment]
最好还是升级下 Extension 呀，如果 Extension 没有重要的 bug 修复，在版本检测配置里我不会去调整对于 Extension 的要求的（即可能会出现 composer 版本是 1.5.2，但是可以用低版本的如 1.5.1 的 Extension 跑）。
