### ISSUE TITLE
[bug] Yii2协程里操作数据库MySQL：Cannot execute queries while other unbuffered queries are active等多个异常

### ISSUE THREAD

**Issue by stevennight** [swow/swow#255]
**Describe the bug / 问题描述**
Yii2协程里操作数据库MySQL（2个协程）：Cannot execute queries while other unbuffered queries are active
如果2个以上协程
Caused by: PHP Warning 'yii\base\ErrorException' with message 'Packets out of order. Expected 11 received 1. Packet size=1'
Next yii\db\Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**To Reproduce / 如何复现**
1. 新建协程（2个以上） Coroutine::run()
2. 协程里面调用Yii2 Model进行查询（one()）
3. 抛出异常

刚关注，请问是可以这样使用的吗？

**Expected behavior / 正确的行为**
正常查询

**Outputs / 程序输出**
2个协程：
```
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
The SQL being executed was: '

in /opt/www/vendor/yiisoft/yii2/db/Schema.php:676

Error Info:
Array
(
    [0] => HY000
    [1] => 2014
    [2] => Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.'

in /opt/www/vendor/yiisoft/yii2/db/Command.php:1320

Stack trace:
#0 /opt/www/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /opt/www/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('SELECT * FROM `...')
#2 /opt/www/vendor/yiisoft/yii2/db/Command.php(431): yii\db\Command->queryInternal('fetch', NULL)
#3 /opt/www/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Command->queryOne()
#4 /opt/www/vendor/yiisoft/yii2/db/ActiveQuery.php(304): yii\db\Query->one(NULL)
#9 {main}
```

2个以上协程：
```
Exception 'yii\db\Exception' with message 'Packets out of order. Expected 11 received 1. Packet size=1
The SQL being executed was: '

in /opt/www/vendor/yiisoft/yii2/db/Schema.php:676

PHP Warning:  Packets out of order. Expected 12 received 0. Packet size=25350 in /opt/www/vendor/yiisoft/yii2/db/Command.php on line 1320
PHP Stack trace:
PHP   1. {fiber:7F35244FF2A0}() /opt/www/services/attendanceSync/v3/fetchData/feishu/FeishuShiftSyncService.php:116
PHP   2. app\services\attendanceSync\v3\fetchData\feishu\FeishuShiftSyncService->app\services\attendanceSync\v3\fetchData\feishu\{closure:/opt/www/services/attendanceSync/v3/fetchData/feishu/FeishuShiftSyncService.php:116-119}() /opt/www/services/attendanceSync/v3/fetchData/feishu/FeishuShiftSyncService.php:116
PHP   3. app\services\attendanceSync\v3\fetchData\feishu\FeishuShiftSyncService->handleAShift() /opt/wwwervices/attendanceSync/v3/fetchData/feishu/FeishuShiftSyncService.php:117
PHP   4. app\models\dao\AttendanceV3ShiftVersionDao->getLastByShiftId() /opt/www/services/attendanceSync/v3/fetchData/feishu/FeishuShiftSyncService.php:137
PHP   5. yii\db\ActiveQuery->one($db = *uninitialized*) /opt/www/models/dao/AttendanceV3ShiftVersionDao.php:33
PHP   6. yii\db\Query->one($db = NULL) /opt/www/vendor/yiisoft/yii2/db/ActiveQuery.php:304
PHP   7. yii\db\Command->queryOne($fetchMode = *uninitialized*) /opt/www/vendor/yiisoft/yii2/db/Query.php:287
PHP   8. yii\db\Command->queryInternal($method = 'fetch', $fetchMode = NULL) /opt/www/vendor/yiisoft/yii2/db/Command.php:431
PHP   9. yii\db\Command->internalExecute($rawSql = 'SELECT * FROM `oa_attendance_v3_shift_version` WHERE (`source_type`=\'feishu\') AND (`shift_id`=\'7234388652410257411\') ORDER BY `id` DESC LIMIT 1') /opt/www/vendor/yiisoft/yii2/db/Command.php:1186
PHP  10. PDOStatement->execute() /opt/www/vendor/yiisoft/yii2/db/Command.php:1320
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /opt/www/vendor/yiisoft/yii2/db/Command.php:1320
Stack trace:
#0 /opt/www/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /opt/www/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('SELECT * FROM `...')
#2 /opt/www/vendor/yiisoft/yii2/db/Command.php(431): yii\db\Command->queryInternal('fetch', NULL)
#3 /opt/www/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Command->queryOne()
#4 /opt/www/vendor/yiisoft/yii2/db/ActiveQuery.php(304): yii\db\Query->one(NULL)
#9 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
The SQL being executed was: in /opt/www/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /opt/www/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'SELECT * FROM `...')
#1 /opt/www/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('SELECT * FROM `...')
#2 /opt/www/vendor/yiisoft/yii2/db/Command.php(431): yii\db\Command->queryInternal('fetch', NULL)
#3 /opt/www/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Command->queryOne()
#4 /opt/www/vendor/yiisoft/yii2/db/ActiveQuery.php(304): yii\db\Query->one(NULL)
#9 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)

  thrown in /opt/www/vendor/yiisoft/yii2/db/Schema.php on line 676
PHP Stack trace:
PHP   1. {fiber:7F35244FF2A0}() /opt/www/services/attendanceSync/v3/fetchData/feishu/FeishuShiftSyncService.php:116
Caused by: PHP Warning 'yii\base\ErrorException' with message 'Packets out of order. Expected 11 received 1. Packet size=1'

in /opt/www/vendor/yiisoft/yii2/db/Command.php:1320

Stack trace:
#0 /opt/www/vendor/yiisoft/yii2/db/Command.php(1320): yii\console\ErrorHandler->handleError(code: '2', message: ''Packets out of...', file: ''/opt/www/vendo...', line: '1320')
#1 /opt/www/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#2 /opt/www/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute(rawSql: ''SELECT * FROM ...')
#3 /opt/www/vendor/yiisoft/yii2/db/Command.php(431): yii\db\Command->queryInternal(method: ''fetch'', fetchMode: 'NULL')
#4 /opt/www/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Command->queryOne(fetchMode: '???')
#5 /opt/www/vendor/yiisoft/yii2/db/ActiveQuery.php(304): yii\db\ActiveQuery->one(db: 'NULL')
#10 {main}
```

**Runtime Environment / 运行环境**
docker php:8.3.9-fpm-alpine
Swow: 1.5.3
Yii2 2.0.51

**Additional context / 补充说明**

**Comment by twose** [comment]
没了解过 Yii2，问题原因很清楚，是因为两个协程同时使用了一个数据库连接，这个得看 Yii2 能不能支持在不同协程里指定不同的数据库连接实例去操作数据库了。不过如果能用 Hyperf 之类的协程框架就不用操心这些了。

**Comment by AuroraYolo** [comment]
yii2的数据库实例都是全局单例
